# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/mnt/c/Users/Ishe/Desktop/Ishe/1. COS 214 - Software Modelling/Google Test"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/mnt/c/Users/Ishe/Desktop/Ishe/1. COS 214 - Software Modelling/Google Test"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/c/Users/Ishe/Desktop/Ishe/1. COS 214 - Software Modelling/Google Test/CMakeFiles" "/mnt/c/Users/Ishe/Desktop/Ishe/1. COS 214 - Software Modelling/Google Test/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/c/Users/Ishe/Desktop/Ishe/1. COS 214 - Software Modelling/Google Test/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named builderTest

# Build rule for target.
builderTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 builderTest
.PHONY : builderTest

# fast build rule for target.
builderTest/fast:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/build
.PHONY : builderTest/fast

BuilderPattern_Test.o: BuilderPattern_Test.cpp.o

.PHONY : BuilderPattern_Test.o

# target to build an object file
BuilderPattern_Test.cpp.o:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/BuilderPattern_Test.cpp.o
.PHONY : BuilderPattern_Test.cpp.o

BuilderPattern_Test.i: BuilderPattern_Test.cpp.i

.PHONY : BuilderPattern_Test.i

# target to preprocess a source file
BuilderPattern_Test.cpp.i:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/BuilderPattern_Test.cpp.i
.PHONY : BuilderPattern_Test.cpp.i

BuilderPattern_Test.s: BuilderPattern_Test.cpp.s

.PHONY : BuilderPattern_Test.s

# target to generate assembly for a file
BuilderPattern_Test.cpp.s:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/BuilderPattern_Test.cpp.s
.PHONY : BuilderPattern_Test.cpp.s

Command.o: Command.cpp.o

.PHONY : Command.o

# target to build an object file
Command.cpp.o:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/Command.cpp.o
.PHONY : Command.cpp.o

Command.i: Command.cpp.i

.PHONY : Command.i

# target to preprocess a source file
Command.cpp.i:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/Command.cpp.i
.PHONY : Command.cpp.i

Command.s: Command.cpp.s

.PHONY : Command.s

# target to generate assembly for a file
Command.cpp.s:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/Command.cpp.s
.PHONY : Command.cpp.s

Controller.o: Controller.cpp.o

.PHONY : Controller.o

# target to build an object file
Controller.cpp.o:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/Controller.cpp.o
.PHONY : Controller.cpp.o

Controller.i: Controller.cpp.i

.PHONY : Controller.i

# target to preprocess a source file
Controller.cpp.i:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/Controller.cpp.i
.PHONY : Controller.cpp.i

Controller.s: Controller.cpp.s

.PHONY : Controller.s

# target to generate assembly for a file
Controller.cpp.s:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/Controller.cpp.s
.PHONY : Controller.cpp.s

CrewDragon.o: CrewDragon.cpp.o

.PHONY : CrewDragon.o

# target to build an object file
CrewDragon.cpp.o:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/CrewDragon.cpp.o
.PHONY : CrewDragon.cpp.o

CrewDragon.i: CrewDragon.cpp.i

.PHONY : CrewDragon.i

# target to preprocess a source file
CrewDragon.cpp.i:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/CrewDragon.cpp.i
.PHONY : CrewDragon.cpp.i

CrewDragon.s: CrewDragon.cpp.s

.PHONY : CrewDragon.s

# target to generate assembly for a file
CrewDragon.cpp.s:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/CrewDragon.cpp.s
.PHONY : CrewDragon.cpp.s

CrewDragonCreator.o: CrewDragonCreator.cpp.o

.PHONY : CrewDragonCreator.o

# target to build an object file
CrewDragonCreator.cpp.o:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/CrewDragonCreator.cpp.o
.PHONY : CrewDragonCreator.cpp.o

CrewDragonCreator.i: CrewDragonCreator.cpp.i

.PHONY : CrewDragonCreator.i

# target to preprocess a source file
CrewDragonCreator.cpp.i:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/CrewDragonCreator.cpp.i
.PHONY : CrewDragonCreator.cpp.i

CrewDragonCreator.s: CrewDragonCreator.cpp.s

.PHONY : CrewDragonCreator.s

# target to generate assembly for a file
CrewDragonCreator.cpp.s:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/CrewDragonCreator.cpp.s
.PHONY : CrewDragonCreator.cpp.s

Dragon.o: Dragon.cpp.o

.PHONY : Dragon.o

# target to build an object file
Dragon.cpp.o:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/Dragon.cpp.o
.PHONY : Dragon.cpp.o

Dragon.i: Dragon.cpp.i

.PHONY : Dragon.i

# target to preprocess a source file
Dragon.cpp.i:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/Dragon.cpp.i
.PHONY : Dragon.cpp.i

Dragon.s: Dragon.cpp.s

.PHONY : Dragon.s

# target to generate assembly for a file
Dragon.cpp.s:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/Dragon.cpp.s
.PHONY : Dragon.cpp.s

DragonCreator.o: DragonCreator.cpp.o

.PHONY : DragonCreator.o

# target to build an object file
DragonCreator.cpp.o:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/DragonCreator.cpp.o
.PHONY : DragonCreator.cpp.o

DragonCreator.i: DragonCreator.cpp.i

.PHONY : DragonCreator.i

# target to preprocess a source file
DragonCreator.cpp.i:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/DragonCreator.cpp.i
.PHONY : DragonCreator.cpp.i

DragonCreator.s: DragonCreator.cpp.s

.PHONY : DragonCreator.s

# target to generate assembly for a file
DragonCreator.cpp.s:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/DragonCreator.cpp.s
.PHONY : DragonCreator.cpp.s

FalconHeavy.o: FalconHeavy.cpp.o

.PHONY : FalconHeavy.o

# target to build an object file
FalconHeavy.cpp.o:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/FalconHeavy.cpp.o
.PHONY : FalconHeavy.cpp.o

FalconHeavy.i: FalconHeavy.cpp.i

.PHONY : FalconHeavy.i

# target to preprocess a source file
FalconHeavy.cpp.i:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/FalconHeavy.cpp.i
.PHONY : FalconHeavy.cpp.i

FalconHeavy.s: FalconHeavy.cpp.s

.PHONY : FalconHeavy.s

# target to generate assembly for a file
FalconHeavy.cpp.s:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/FalconHeavy.cpp.s
.PHONY : FalconHeavy.cpp.s

FalconNine.o: FalconNine.cpp.o

.PHONY : FalconNine.o

# target to build an object file
FalconNine.cpp.o:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/FalconNine.cpp.o
.PHONY : FalconNine.cpp.o

FalconNine.i: FalconNine.cpp.i

.PHONY : FalconNine.i

# target to preprocess a source file
FalconNine.cpp.i:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/FalconNine.cpp.i
.PHONY : FalconNine.cpp.i

FalconNine.s: FalconNine.cpp.s

.PHONY : FalconNine.s

# target to generate assembly for a file
FalconNine.cpp.s:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/FalconNine.cpp.s
.PHONY : FalconNine.cpp.s

HaltCommand.o: HaltCommand.cpp.o

.PHONY : HaltCommand.o

# target to build an object file
HaltCommand.cpp.o:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/HaltCommand.cpp.o
.PHONY : HaltCommand.cpp.o

HaltCommand.i: HaltCommand.cpp.i

.PHONY : HaltCommand.i

# target to preprocess a source file
HaltCommand.cpp.i:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/HaltCommand.cpp.i
.PHONY : HaltCommand.cpp.i

HaltCommand.s: HaltCommand.cpp.s

.PHONY : HaltCommand.s

# target to generate assembly for a file
HaltCommand.cpp.s:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/HaltCommand.cpp.s
.PHONY : HaltCommand.cpp.s

LaunchCommand.o: LaunchCommand.cpp.o

.PHONY : LaunchCommand.o

# target to build an object file
LaunchCommand.cpp.o:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/LaunchCommand.cpp.o
.PHONY : LaunchCommand.cpp.o

LaunchCommand.i: LaunchCommand.cpp.i

.PHONY : LaunchCommand.i

# target to preprocess a source file
LaunchCommand.cpp.i:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/LaunchCommand.cpp.i
.PHONY : LaunchCommand.cpp.i

LaunchCommand.s: LaunchCommand.cpp.s

.PHONY : LaunchCommand.s

# target to generate assembly for a file
LaunchCommand.cpp.s:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/LaunchCommand.cpp.s
.PHONY : LaunchCommand.cpp.s

Rocket.o: Rocket.cpp.o

.PHONY : Rocket.o

# target to build an object file
Rocket.cpp.o:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/Rocket.cpp.o
.PHONY : Rocket.cpp.o

Rocket.i: Rocket.cpp.i

.PHONY : Rocket.i

# target to preprocess a source file
Rocket.cpp.i:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/Rocket.cpp.i
.PHONY : Rocket.cpp.i

Rocket.s: Rocket.cpp.s

.PHONY : Rocket.s

# target to generate assembly for a file
Rocket.cpp.s:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/Rocket.cpp.s
.PHONY : Rocket.cpp.s

ShuttleState.o: ShuttleState.cpp.o

.PHONY : ShuttleState.o

# target to build an object file
ShuttleState.cpp.o:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/ShuttleState.cpp.o
.PHONY : ShuttleState.cpp.o

ShuttleState.i: ShuttleState.cpp.i

.PHONY : ShuttleState.i

# target to preprocess a source file
ShuttleState.cpp.i:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/ShuttleState.cpp.i
.PHONY : ShuttleState.cpp.i

ShuttleState.s: ShuttleState.cpp.s

.PHONY : ShuttleState.s

# target to generate assembly for a file
ShuttleState.cpp.s:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/ShuttleState.cpp.s
.PHONY : ShuttleState.cpp.s

SpaceCraft.o: SpaceCraft.cpp.o

.PHONY : SpaceCraft.o

# target to build an object file
SpaceCraft.cpp.o:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/SpaceCraft.cpp.o
.PHONY : SpaceCraft.cpp.o

SpaceCraft.i: SpaceCraft.cpp.i

.PHONY : SpaceCraft.i

# target to preprocess a source file
SpaceCraft.cpp.i:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/SpaceCraft.cpp.i
.PHONY : SpaceCraft.cpp.i

SpaceCraft.s: SpaceCraft.cpp.s

.PHONY : SpaceCraft.s

# target to generate assembly for a file
SpaceCraft.cpp.s:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/SpaceCraft.cpp.s
.PHONY : SpaceCraft.cpp.s

SpaceShuttle.o: SpaceShuttle.cpp.o

.PHONY : SpaceShuttle.o

# target to build an object file
SpaceShuttle.cpp.o:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/SpaceShuttle.cpp.o
.PHONY : SpaceShuttle.cpp.o

SpaceShuttle.i: SpaceShuttle.cpp.i

.PHONY : SpaceShuttle.i

# target to preprocess a source file
SpaceShuttle.cpp.i:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/SpaceShuttle.cpp.i
.PHONY : SpaceShuttle.cpp.i

SpaceShuttle.s: SpaceShuttle.cpp.s

.PHONY : SpaceShuttle.s

# target to generate assembly for a file
SpaceShuttle.cpp.s:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/SpaceShuttle.cpp.s
.PHONY : SpaceShuttle.cpp.s

SpaceShuttleBuilder.o: SpaceShuttleBuilder.cpp.o

.PHONY : SpaceShuttleBuilder.o

# target to build an object file
SpaceShuttleBuilder.cpp.o:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/SpaceShuttleBuilder.cpp.o
.PHONY : SpaceShuttleBuilder.cpp.o

SpaceShuttleBuilder.i: SpaceShuttleBuilder.cpp.i

.PHONY : SpaceShuttleBuilder.i

# target to preprocess a source file
SpaceShuttleBuilder.cpp.i:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/SpaceShuttleBuilder.cpp.i
.PHONY : SpaceShuttleBuilder.cpp.i

SpaceShuttleBuilder.s: SpaceShuttleBuilder.cpp.s

.PHONY : SpaceShuttleBuilder.s

# target to generate assembly for a file
SpaceShuttleBuilder.cpp.s:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/SpaceShuttleBuilder.cpp.s
.PHONY : SpaceShuttleBuilder.cpp.s

SpaceX.o: SpaceX.cpp.o

.PHONY : SpaceX.o

# target to build an object file
SpaceX.cpp.o:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/SpaceX.cpp.o
.PHONY : SpaceX.cpp.o

SpaceX.i: SpaceX.cpp.i

.PHONY : SpaceX.i

# target to preprocess a source file
SpaceX.cpp.i:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/SpaceX.cpp.i
.PHONY : SpaceX.cpp.i

SpaceX.s: SpaceX.cpp.s

.PHONY : SpaceX.s

# target to generate assembly for a file
SpaceX.cpp.s:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/SpaceX.cpp.s
.PHONY : SpaceX.cpp.s

Stage1.o: Stage1.cpp.o

.PHONY : Stage1.o

# target to build an object file
Stage1.cpp.o:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/Stage1.cpp.o
.PHONY : Stage1.cpp.o

Stage1.i: Stage1.cpp.i

.PHONY : Stage1.i

# target to preprocess a source file
Stage1.cpp.i:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/Stage1.cpp.i
.PHONY : Stage1.cpp.i

Stage1.s: Stage1.cpp.s

.PHONY : Stage1.s

# target to generate assembly for a file
Stage1.cpp.s:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/Stage1.cpp.s
.PHONY : Stage1.cpp.s

Stage2.o: Stage2.cpp.o

.PHONY : Stage2.o

# target to build an object file
Stage2.cpp.o:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/Stage2.cpp.o
.PHONY : Stage2.cpp.o

Stage2.i: Stage2.cpp.i

.PHONY : Stage2.i

# target to preprocess a source file
Stage2.cpp.i:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/Stage2.cpp.i
.PHONY : Stage2.cpp.i

Stage2.s: Stage2.cpp.s

.PHONY : Stage2.s

# target to generate assembly for a file
Stage2.cpp.s:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/Stage2.cpp.s
.PHONY : Stage2.cpp.s

Starlink.o: Starlink.cpp.o

.PHONY : Starlink.o

# target to build an object file
Starlink.cpp.o:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/Starlink.cpp.o
.PHONY : Starlink.cpp.o

Starlink.i: Starlink.cpp.i

.PHONY : Starlink.i

# target to preprocess a source file
Starlink.cpp.i:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/Starlink.cpp.i
.PHONY : Starlink.cpp.i

Starlink.s: Starlink.cpp.s

.PHONY : Starlink.s

# target to generate assembly for a file
Starlink.cpp.s:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/Starlink.cpp.s
.PHONY : Starlink.cpp.s

State.o: State.cpp.o

.PHONY : State.o

# target to build an object file
State.cpp.o:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/State.cpp.o
.PHONY : State.cpp.o

State.i: State.cpp.i

.PHONY : State.i

# target to preprocess a source file
State.cpp.i:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/State.cpp.i
.PHONY : State.cpp.i

State.s: State.cpp.s

.PHONY : State.s

# target to generate assembly for a file
State.cpp.s:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/State.cpp.s
.PHONY : State.cpp.s

WinningConfig.o: WinningConfig.cpp.o

.PHONY : WinningConfig.o

# target to build an object file
WinningConfig.cpp.o:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/WinningConfig.cpp.o
.PHONY : WinningConfig.cpp.o

WinningConfig.i: WinningConfig.cpp.i

.PHONY : WinningConfig.i

# target to preprocess a source file
WinningConfig.cpp.i:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/WinningConfig.cpp.i
.PHONY : WinningConfig.cpp.i

WinningConfig.s: WinningConfig.cpp.s

.PHONY : WinningConfig.s

# target to generate assembly for a file
WinningConfig.cpp.s:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/WinningConfig.cpp.s
.PHONY : WinningConfig.cpp.s

WinningShuttle.o: WinningShuttle.cpp.o

.PHONY : WinningShuttle.o

# target to build an object file
WinningShuttle.cpp.o:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/WinningShuttle.cpp.o
.PHONY : WinningShuttle.cpp.o

WinningShuttle.i: WinningShuttle.cpp.i

.PHONY : WinningShuttle.i

# target to preprocess a source file
WinningShuttle.cpp.i:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/WinningShuttle.cpp.i
.PHONY : WinningShuttle.cpp.i

WinningShuttle.s: WinningShuttle.cpp.s

.PHONY : WinningShuttle.s

# target to generate assembly for a file
WinningShuttle.cpp.s:
	$(MAKE) -f CMakeFiles/builderTest.dir/build.make CMakeFiles/builderTest.dir/WinningShuttle.cpp.s
.PHONY : WinningShuttle.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... builderTest"
	@echo "... BuilderPattern_Test.o"
	@echo "... BuilderPattern_Test.i"
	@echo "... BuilderPattern_Test.s"
	@echo "... Command.o"
	@echo "... Command.i"
	@echo "... Command.s"
	@echo "... Controller.o"
	@echo "... Controller.i"
	@echo "... Controller.s"
	@echo "... CrewDragon.o"
	@echo "... CrewDragon.i"
	@echo "... CrewDragon.s"
	@echo "... CrewDragonCreator.o"
	@echo "... CrewDragonCreator.i"
	@echo "... CrewDragonCreator.s"
	@echo "... Dragon.o"
	@echo "... Dragon.i"
	@echo "... Dragon.s"
	@echo "... DragonCreator.o"
	@echo "... DragonCreator.i"
	@echo "... DragonCreator.s"
	@echo "... FalconHeavy.o"
	@echo "... FalconHeavy.i"
	@echo "... FalconHeavy.s"
	@echo "... FalconNine.o"
	@echo "... FalconNine.i"
	@echo "... FalconNine.s"
	@echo "... HaltCommand.o"
	@echo "... HaltCommand.i"
	@echo "... HaltCommand.s"
	@echo "... LaunchCommand.o"
	@echo "... LaunchCommand.i"
	@echo "... LaunchCommand.s"
	@echo "... Rocket.o"
	@echo "... Rocket.i"
	@echo "... Rocket.s"
	@echo "... ShuttleState.o"
	@echo "... ShuttleState.i"
	@echo "... ShuttleState.s"
	@echo "... SpaceCraft.o"
	@echo "... SpaceCraft.i"
	@echo "... SpaceCraft.s"
	@echo "... SpaceShuttle.o"
	@echo "... SpaceShuttle.i"
	@echo "... SpaceShuttle.s"
	@echo "... SpaceShuttleBuilder.o"
	@echo "... SpaceShuttleBuilder.i"
	@echo "... SpaceShuttleBuilder.s"
	@echo "... SpaceX.o"
	@echo "... SpaceX.i"
	@echo "... SpaceX.s"
	@echo "... Stage1.o"
	@echo "... Stage1.i"
	@echo "... Stage1.s"
	@echo "... Stage2.o"
	@echo "... Stage2.i"
	@echo "... Stage2.s"
	@echo "... Starlink.o"
	@echo "... Starlink.i"
	@echo "... Starlink.s"
	@echo "... State.o"
	@echo "... State.i"
	@echo "... State.s"
	@echo "... WinningConfig.o"
	@echo "... WinningConfig.i"
	@echo "... WinningConfig.s"
	@echo "... WinningShuttle.o"
	@echo "... WinningShuttle.i"
	@echo "... WinningShuttle.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

